on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Updates Youtube Sub Count
    steps:
      - uses: actions/checkout@v3
      - name: Updates Youtube Sub Count
        uses: WeiYun0912/youtube-sub-action@main
